language: go

go:
  - "1.12.x"

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.19.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

jobs:
  include:
    - stage: build
      script:
        - make test
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make docker-login images-push; fi'
    - stage: coverage
      script:
        - make coverage
